### ISSUE TITLE
to-do for 2.4.0

### ISSUE THREAD

**Issue by kenirwin** [Miamiohlibs/SoftwareCheckout2#110]
- [x] update documentation
  - [x] server
  - [x] cron stats
  - [x] changes to config
  - [x] run under pm2
  - [x] explain uid - one per web restart and one per time the app runs (adobe vs. jamf?) 
- [x] test in production
- [x] error handling for web routes (see #133)
- [x] add/update changelog
- [x] check for any npm package updates / security audit
